### ISSUE TITLE
Add Elysia as a Fastify alternative

### ISSUE THREAD

**Issue by kravetsone** [kitajs/kitajs#235]
Maybe add [Elysia](https://elysiajs.com/)?
Elysia is a bun web framework with great prefomance and DX!

**Comment by arthurfiorette** [comment]
Although I really like Elysia, its nowhere near in a production ready state, Elysia is awesome and SaltyAom is an awesome dev but more people need to use it. If saltyaom decides to stop maintaining it, it will be dead in a week and there wont even be enough people using it to build a community around it. Kita is also in this state, but Kita can be in this state and be considered production ready because none of its code is ran at runtime and all of its primary dependencies (`fastify` and `ts-json-schema-generator`) are long tested projects.

Also, another major pain point is their schema, which does not follows JSON schema standard, so a hand build "converter" would be needed as their schema is kind of proprietary.

**Comment by kravetsone** [comment]
> Also, another major pain point is their schema, which does not follows JSON schema standard, so a hand build "converter" would be needed as their schema is kind of proprietary.

TypeBox is a runtime type builder that creates in-memory Json Schema objects that infer as TypeScript types. 

> Although I really like Elysia, its nowhere near in a production ready state


Unfortunately, this is true at the moment. But I think this project has a good future) and if we all don't be afraid but try to develop, then we will succeed!

Your project is also very interesting! Github explore accidentally showed it to me) It is somewhat similar to [fastapi](https://fastapi.tiangolo.com/)

**Comment by kravetsone** [comment]
You know [typia](https://typia.io/)? Typia does a similar validation)

**Comment by arthurfiorette** [comment]
> TypeBox is a runtime type builder that creates in-memory Json Schema objects that infer as TypeScript types.

Hmm, maybe I was wrong, I'd take a better look into maybe adding support to elysia...

> But I think this project has a good future) and if we all don't be afraid but try to develop, then we will succeed!

One statistic I like to lookup is the downloads/star ratio, I even [made a tweet about it sometime ago](https://twitter.com/arthurfiorette/status/1738717891850072129). This tweet does not applies 100% here, but Elysia has 14K downloads/week and 6K stars, this ratio clearly shows the project's growth through influence and not because it is good/used enough. Only time will tell us.

> Your project is also very interesting! Github explore accidentally showed it to me) It is somewhat similar to [fastapi](https://fastapi.tiangolo.com/)

Thanks! It's already production ready, but its documentation isn't, that's why I'm not promoting it yet... I would love any feedback :) [Keddit](https://github.com/kitajs/keddit) is the best place to learn kita so far.

> You know [typia](https://typia.io/)? Typia does a similar validation)

I do, currently `ajv` is being used, but not because it was my choice, only because that's what fastify uses under the hood.

**Comment by kravetsone** [comment]
> Hmm, maybe I was wrong, I'd take a better look into maybe adding support to elysia...

Or me. I mentioned that TypeBox generates a JSON SCHEMA, but you can't insert the json schema itself into options.

But maybe you can use for example `typia` (I think this will be a faster) with validation in life-cycle hooks)

And we can talk about this with maintainer) I love Elysia and it's perfomance with Bun

If we can reach this with `kita` thats will be great! 

Well, it's more like thinking about the future

and kita is already a wonderful find) I will follow the development of the project

**Comment by kravetsone** [comment]
I would also like to see decorators in js... together with them, kita would be even more convenient)

**Comment by arthurfiorette** [comment]
> I would also like to see decorators in js... together with them, kita would be even more convenient)

That's the intent of providers, to be able to do everything a "decorator" would do (cannot use decorators in pure functions) with support for type inference and more...
